apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'travel-orchestrator'
        static_configs:
          - targets: ['travel-orchestrator:8000']

      - job_name: 'flight-service'
        static_configs:
          - targets: ['flight-service:8000']

      - job_name: 'hotel-service'
        static_configs:
          - targets: ['hotel-service:8001']

      - job_name: 'activity-service'
        static_configs:
          - targets: ['activity-service:8002']

      - job_name: 'geocoding-service'
        static_configs:
          - targets: ['geocoding-service:8003']

      - job_name: 'event-service'
        static_configs:
          - targets: ['event-service:8004']